#!/usr/bin/env bash

set -euo pipefail

bundle exec middleman build --verbose

mv build/sitemap.xml build/docs/sitemap.xml
mv build/sitemap.xml.gz build/docs/sitemap.xml.gz

aws --profile=rt s3 sync build/ s3://semaphore-classic-docs/ --acl=public-read --delete --cache-control="max-age=0, no-cache" --exclude "logs/*"
