#!/usr/bin/env bash

if ! [ -e data/credentials.yml ]; then
  cp data/credentials.yml.example data/credentials.yml 
fi

bundle install

echo '                                                               '
echo '  mmmm                              #                          '
echo ' #"   "  mmm   mmmmm   mmm   mmmm   # mm    mmm    m mm   mmm  '
echo ' "#mmm  #"  #  # # #  "   #  #" "#  #"  #  #" "#   #"  " #"  # '
echo '     "# #""""  # # #  m"""#  #   #  #   #  #   #   #     #"""" '
echo ' "mmm#" "#mm"  # # #  "mm"#  ##m#"  #   #  "#m#"   #     "#mm" '
echo '                             #                                 '
echo ' localhost:4000/docs         "                   DOCUMENTATION '
echo '                                                               '

bundle exec middleman -p 4000 -h "0.0.0.0"
