#!/bin/bash

design_repo="${PWD%/*}/semaphore-design"
assets_source="${design_repo}/community/public/assets"

if [[ ! -e "$design_repo" ]]; then
  echo -e "Please clone semaphore-design repo to $design_repo"
  exit
fi

# Copy assets
rsync -r $assets_source/images/* source/docs/assets/img/
cp -r $assets_source/css/* source/docs/assets/css/
cp -r $assets_source/js/* source/docs/assets/js/

# Convert plain image paths to asset paths
sed -i 's/..\/images/\/docs\/assets\/img/g' source/docs/assets/css/*
