#!/bin/bash

design_repo="${PWD%/*}/semaphore-design/community/public"

if [[ ! -e "$design_repo" ]]; then
  echo -e "Please clone community-design repo to $design_repo"
  exit
fi

# Copy assets
rsync -r $design_repo/assets/images/* source/docs/assets/img/
cp -r $design_repo/assets/css/* source/docs/assets/css/
cp -r $design_repo/assets/js/* source/docs/assets/js/

# Convert plain image paths to asset paths
sed -i 's/..\/images/\/docs\/assets\/img/g' source/docs/assets/css/*
