Dir["source/categories/*.rb"].each { |file| require_relative file.split("/").drop(1).join("/") }

def category_options
  case current_page.data.category
  when GETTING_STARTED_KEY then GETTING_STARTED_OPTIONS
  when LANGUAGE_SUPPORT_KEY, *LANGUAGE_SUPPORT_SUBCATEGORIES then LANGUAGE_SUPPORT_OPTIONS
  when DATABASE_SUPPORT_KEY then DATABASE_SUPPORT_OPTIONS
  when DOCKER_SUPPORT_KEY then DOCKER_SUPPORT_OPTIONS
  when SEMAPHORE_PLATFORM_KEY then SEMAPHORE_PLATFORM_OPTIONS
  when GIT_SERVICES_KEY then GIT_SERVICES_OPTIONS
  when BUILD_CUSTOMIZATION_KEY then BUILD_CUSTOMIZATION_OPTIONS
  when ADAPTING_SEMAPHORE_KEY then ADAPTING_SEMAPHORE_OPTIONS
  when MANAGING_DEPENDENCIES_KEY then MANAGING_DEPENDENCIES_OPTIONS
  when BUILD_TROUBLESHOOTING_KEY then BUILD_TROUBLESHOOTING_OPTIONS
  when DEPLOYMENT_KEY then DEPLOYMENT_OPTIONS
  when INSIGHTS_KEY then INSIGHTS_OPTIONS
  when COLLABORATION_KEY then COLLABORATION_OPTIONS
  when ORGANIZATIONS_KEY then ORGANIZATIONS_OPTIONS
  when TWO_STEP_VERIFICATION_KEY then TWO_STEP_VERIFICATION_OPTIONS
  when NOTIFICATIONS_KEY then NOTIFICATIONS_OPTIONS
  else []
  end
end
